### ISSUE TITLE
Error querying all nodes after buffering change in 4.0

### ISSUE THREAD

**Issue by aakashjhawar** [sagastume/boltx#67] opened 2024-02-01 09:53 UTC
I am getting this error while querying using Boltx. The same query works if I try it on the Neo4j Browser. 

```
** (DBConnection.ConnectionError) bad return value: {:error, %{code: :failure, message: %MatchError{term: << 101, 91, 100,  102, 81, 101, 107, 111, 109, 111, 42, ...>>}}}
    (db_connection 2.6.0) lib/db_connection.ex:1366: DBConnection.handle_common_result/3
    (db_connection 2.6.0) lib/db_connection.ex:1607: DBConnection.run/6
    (db_connection 2.6.0) lib/db_connection.ex:743: DBConnection.parsed_prepare_execute/5
    (db_connection 2.6.0) lib/db_connection.ex:735: DBConnection.prepare_execute/4
    (boltx 0.0.5) lib/boltx.ex:149: Boltx.do_query/4
```

Can you please check this?

**Comment by sagastume** [comment] 2024-02-01 13:31
Thank you,

Could you tell me what query you are executing?

**Comment by aakashjhawar** [comment] 2024-02-02 06:50
Hi @sagastume, I'm getting this error at multiple places. 

Sharing one instance, where it breaks. When I do `MATCH(n) RETURN(n)`, it throws an error. I'm able to get the response when I use BoltSips or even Neo4j Python driver.

iex>query = "MATCH(n) RETURN(n)"
iex> Boltx.query(Bolt, query)
```
** (BadMapError) expected a map, got: nil
    (elixir 1.14.5) lib/map.ex:534: Map.get(nil, "plan", nil)
    (boltx 0.0.5) lib/boltx/response.ex:49: Boltx.Response.new/1
    (boltx 0.0.5) lib/boltx/connection.ex:130: Boltx.Connection.result/3
    (db_connection 2.6.0) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.6.0) lib/db_connection.ex:1512: DBConnection.run_execute/5
    (db_connection 2.6.0) lib/db_connection.ex:1607: DBConnection.run/6
    (db_connection 2.6.0) lib/db_connection.ex:743: DBConnection.parsed_prepare_execute/5
    (db_connection 2.6.0) lib/db_connection.ex:735: DBConnection.prepare_execute/4
```

Thank you.

**Comment by sagastume** [comment] 2024-02-02 14:52
This error is distinct from the initial one 🤔 
Could you tell me which version of Neo4j your instance is using?

**Comment by aakashjhawar** [comment] 2024-02-04 13:00
I'm using 5.13.0 version of Neo4j.

To replicate the 2nd error please follow the steps. 

1. Create nodes in the database using the following script.
```
query = "CREATE (country:Country {name:'C1', created_at: datetime(), id: randomUUID()})"
Boltx.query(Bolt, query)

Enum.each(0..99, fn(x) -> 
    query = """
    MATCH(country:Country{name: 'C1'})
    CREATE (city:City {name:'City_#{x}', created_at: datetime(), id: randomUUID()})
    CREATE (country)-[:has_city{created_at: datetime(), id: randomUUID()}]->(city)
    """
    Boltx.query(Bolt, query)
 end)
```

2. Post this, when we try to fetch all the nodes using this query, we get the error.

```
query = "MATCH(n) RETURN n"
Boltx.query(Bolt, query)
```

Error:
```
** (BadMapError) expected a map, got: nil
    (elixir 1.14.5) lib/map.ex:534: Map.get(nil, "plan", nil)
    (boltx 0.0.5) lib/boltx/response.ex:49: Boltx.Response.new/1
    (boltx 0.0.5) lib/boltx/connection.ex:130: Boltx.Connection.result/3
    (db_connection 2.6.0) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.6.0) lib/db_connection.ex:1512: DBConnection.run_execute/5
    (db_connection 2.6.0) lib/db_connection.ex:1607: DBConnection.run/6
    (db_connection 2.6.0) lib/db_connection.ex:743: DBConnection.parsed_prepare_execute/5
    (db_connection 2.6.0) lib/db_connection.ex:735: DBConnection.prepare_execute/4
    (boltx 0.0.5) lib/boltx.ex:149: Boltx.do_query/4
```

I am not able to reproduce the 1st error on my local machine. But I do get that error in some of the cases.

Thank you.

**Comment by sagastume** [comment] 2024-02-08 03:13
Thank you @aakashjhawar for providing the steps to replicate.

I will check what the problem is and send fix.

**Comment by aakashjhawar** [comment] 2024-02-12 14:30
Hi @sagastume any updates on this? 

Thanks.

**Comment by sagastume** [comment] 2024-02-12 14:52
Hi @aakashjhawar 

I believe I have identified the issue: when messages of the "Detail message" type (query data) are received from the server, it does not expect a "Summary message" type (indicates whether it is successful or failed). There are moments when the operation succeeds because the "Summary message" is received, but there are also times when it fails because it is not received.

Modifications need to be made to the Client.recv_packets/4 function. I plan to work on this during this week.

The documentation of bolt states:

> Request message - the client sends a message.
> Summary message - the server always responds with one summary message if the connection is still open.
> Detail message - the server always responds with zero or more detail messages before sending a summary message.

**Comment by tlemens** [comment] 2024-02-14 21:19
Hi @sagastume, I have the same error with Neo4j 4.4:

```
[error] ** State machine #PID<0.871.0> terminating
** Reason for termination ==
** (DBConnection.ConnectionError) client #PID<0.1020.0> stopped: ** (BadMapError) expected a map, got: nil
    (elixir 1.15.7) lib/map.ex:535: Map.get(nil, "plan", nil)
    (boltx 0.0.5) lib/boltx/response.ex:49: Boltx.Response.new/1
    (boltx 0.0.5) lib/boltx/connection.ex:130: Boltx.Connection.result/3
    (db_connection 2.6.0) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.6.0) lib/db_connection.ex:1512: DBConnection.run_execute/5
    (db_connection 2.6.0) lib/db_connection.ex:1607: DBConnection.run/6
    (db_connection 2.6.0) lib/db_connection.ex:743: DBConnection.parsed_prepare_execute/5
    (db_connection 2.6.0) lib/db_connection.ex:735: DBConnection.prepare_execute/4
    (boltx 0.0.5) lib/boltx.ex:149: Boltx.do_query/4
    (boltx 0.0.5) lib/boltx.ex:114: Boltx.query!/4
```

Thank you

**Comment by sagastume** [comment] 2024-02-18 22:06
Hi, @aakashjhawar, @tlemens!

Just wanted to keep you updated: I've been working on a solution that so far works for versions 4 onwards, but I'm still dealing with some issues for versions 1.0 to 3.0.

The problem lies in a change implemented from Neo4j version 4.0 onwards. It seems that they no longer store a full buffer when requesting all nodes with `MATCH(n) RETURN n`, but send the data one by one. If you want to follow the changes, you can check the branch associated with this issue.

I hope to fix all this as soon as possible.

**Comment by sagastume** [comment] 2024-02-18 22:38
Solution to be released in version 0.0.6

**Closed** 2024-02-18 22:38 UTC
Labels: bolt v5, bolt v4

**Comment by tlemens** [comment] 2024-02-19 08:48
It works thank you :pray:

**Comment by aakashjhawar** [comment] 2024-02-19 10:10
Thanks @sagastume!
